# Generated by Django 2.1 on 2020-09-13 04:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_backup_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('image_url_hi_res', models.URLField()),
                ('subtype', models.CharField(max_length=100)),
                ('supertype', models.CharField(max_length=100)),
                ('ability', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hp', models.CharField(max_length=5)),
                ('number', models.IntegerField(null=True)),
                ('artist', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=15)),
                ('series', models.CharField(max_length=10)),
                ('set', models.CharField(max_length=10)),
                ('set_code', models.CharField(max_length=10)),
                ('retreat_cost', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('converted_retreat_cost', models.IntegerField(null=True)),
                ('text', django.contrib.postgres.fields.jsonb.JSONField()),
                ('types', django.contrib.postgres.fields.jsonb.JSONField()),
                ('attacks', django.contrib.postgres.fields.jsonb.JSONField()),
                ('weaknesses', django.contrib.postgres.fields.jsonb.JSONField()),
                ('resistances', django.contrib.postgres.fields.jsonb.JSONField()),
                ('evolves_from', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='backups',
            name='data',
        ),
        migrations.AddField(
            model_name='backupitems',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_backup_api.Backups'),
        ),
    ]
