# Generated by Django 2.1 on 2020-09-13 04:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_backup_api', '0002_auto_20200913_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupitems',
            name='ability',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='backupitems',
            name='attacks',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='backupitems',
            name='resistances',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='backupitems',
            name='retreat_cost',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupitems',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='backupitems',
            name='types',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='backupitems',
            name='weaknesses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
