# Generated by Django 2.1 on 2020-09-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_backup_api', '0004_auto_20200913_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupitems',
            name='hp',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
